// Static library passages with hand-authored questions. Extracted from
// student-reading-quest.jsx so Vite can ship it as its own chunk that's
// downloaded in parallel with the main app code (and cached separately).
// startStoryFromLibrary upgrades these short quizzes to level-appropriate
// AI-generated ones at play time — see getLibraryQuiz().

export const STORY_LIBRARY = [
  // ── A1 ──
  {id:"a1_1",level:"A1",title:"My Family",topic:"Family",
   passage:"My name is Tom. I am eight years old. I have a mother, a father, and one sister. My sister is five years old. Her name is Lucy. We live in a small house. Our house has three rooms. We have a dog. The dog's name is Max. Max is big and brown. I love my family very much.",
   questions:[
     {type:"mcq",q:"How old is Tom?",options:["Five","Six","Eight","Ten"],answer:2,explanation:"Tom says 'I am eight years old.'"},
     {type:"mcq",q:"What is the dog's name?",options:["Lucy","Max","Tom","Rex"],answer:1,explanation:"Tom says 'The dog's name is Max.'"},
     {type:"gap_word",sentence:"Tom's sister is ___ years old.",options:["three","five","eight","ten"],answer:1,explanation:"Lucy is five years old."},
   ]},
  {id:"a1_2",level:"A1",title:"At the Market",topic:"Shopping",
   passage:"Every Saturday, my mother goes to the market. She buys fruit and vegetables. She buys apples, bananas, and oranges. She also buys carrots and tomatoes. The market is near our house. It is a ten-minute walk. The fruit is fresh and cheap. My mother loves the market.",
   questions:[
     {type:"mcq",q:"When does the mother go to the market?",options:["Sunday","Monday","Saturday","Friday"],answer:2,explanation:"She goes every Saturday."},
     {type:"mcq",q:"How far is the market?",options:["Five minutes","Ten minutes","Twenty minutes","One hour"],answer:1,explanation:"It is a ten-minute walk."},
     {type:"gap_word",sentence:"The fruit at the market is fresh and ___.",options:["expensive","old","cheap","far"],answer:2,explanation:"The passage says 'fresh and cheap'."},
   ]},
  {id:"a1_3",level:"A1",title:"My School",topic:"School",
   passage:"I go to school every day from Monday to Friday. My school is small. There are twenty students in my class. My teacher's name is Mrs. Green. She is very kind. We study reading, writing, and maths. My favourite subject is maths. School starts at eight o'clock and ends at three o'clock.",
   questions:[
     {type:"mcq",q:"What is the teacher's name?",options:["Mrs. Blue","Mrs. Green","Mrs. Brown","Mrs. White"],answer:1,explanation:"The passage says 'My teacher's name is Mrs. Green.'"},
     {type:"mcq",q:"What is the student's favourite subject?",options:["Reading","Writing","Science","Maths"],answer:3,explanation:"The passage says 'My favourite subject is maths.'"},
     {type:"gap_word",sentence:"There are ___ students in the class.",options:["ten","fifteen","twenty","thirty"],answer:2,explanation:"'There are twenty students in my class.'"},
   ]},
  // ── A2 ──
  {id:"a2_1",level:"A2",title:"The Lost Key",topic:"Daily Life",
   passage:"Yesterday morning, Sarah could not find her house key. She looked everywhere. She checked her bag, her coat pockets, and the kitchen table. Then she remembered — she left it at her friend Anna's house the day before. Sarah called Anna. Anna found the key under the sofa. Sarah was very relieved.",
   questions:[
     {type:"mcq",q:"Where did Sarah leave her key?",options:["In her bag","On the kitchen table","At Anna's house","In her coat pocket"],answer:2,explanation:"She left it at her friend Anna's house."},
     {type:"mcq",q:"Where did Anna find the key?",options:["In her bag","Under the sofa","On the table","By the door"],answer:1,explanation:"Anna found the key under the sofa."},
     {type:"gap_word",sentence:"Sarah felt very ___ when the key was found.",options:["angry","sad","relieved","tired"],answer:2,explanation:"'Sarah was very relieved.'"},
   ]},
  {id:"a2_2",level:"A2",title:"Learning to Cook",topic:"Food",
   passage:"Last summer, Pedro decided to learn how to cook. He watched videos online and bought a simple cookbook. First, he learned to make pasta. It was difficult at first, but he practised every day. After two weeks, his pasta was delicious. His family were very proud of him. Now Pedro cooks dinner every Friday.",
   questions:[
     {type:"mcq",q:"How did Pedro learn to cook?",options:["At school","From his family","Online videos and a cookbook","At a restaurant"],answer:2,explanation:"He watched videos online and bought a cookbook."},
     {type:"mcq",q:"How long did it take before his pasta was delicious?",options:["One week","Two weeks","One month","Three days"],answer:1,explanation:"'After two weeks, his pasta was delicious.'"},
     {type:"gap_word",sentence:"Pedro cooks dinner every ___.",options:["Monday","Wednesday","Sunday","Friday"],answer:3,explanation:"'Now Pedro cooks dinner every Friday.'"},
   ]},
  {id:"a2_3",level:"A2",title:"The New Neighbour",topic:"Community",
   passage:"A new family moved into the house next door last month. They have two children — a boy called Marco and a girl called Lily. Marco is the same age as me, so we go to the same school. Lily is younger; she goes to primary school. Their parents are both doctors. The whole family is very friendly. We often invite them for dinner.",
   questions:[
     {type:"mcq",q:"What do the parents do for work?",options:["Teachers","Doctors","Engineers","Chefs"],answer:1,explanation:"'Their parents are both doctors.'"},
     {type:"mcq",q:"Who goes to the same school as the narrator?",options:["Lily","Marco","Both children","Neither"],answer:1,explanation:"'Marco is the same age as me, so we go to the same school.'"},
     {type:"gap_word",sentence:"The family moved in ___ month.",options:["this","next","last","every"],answer:2,explanation:"'A new family moved into the house next door last month.'"},
   ]},
  // ── B1 ──
  {id:"b1_1",level:"B1",title:"The Power of Habit",topic:"Psychology",
   passage:"Scientists say that about 40% of our daily actions are habits, not decisions. A habit is formed when a behaviour is repeated so often that it becomes automatic. The brain creates a loop: a cue triggers the habit, the routine follows, and then there is a reward. Breaking a bad habit is hard because the brain loop remains even when the behaviour stops. The most effective strategy is not to try to stop the habit but to replace it with a different routine triggered by the same cue.",
   questions:[
     {type:"mcq",q:"What percentage of daily actions are habits according to scientists?",options:["20%","30%","40%","60%"],answer:2,explanation:"The passage states 'about 40% of our daily actions are habits.'"},
     {type:"mcq",q:"What is the most effective strategy for breaking a bad habit?",options:["Stopping it immediately","Avoiding the cue","Replacing it with a different routine","Rewarding yourself"],answer:2,explanation:"'The most effective strategy is to replace it with a different routine.'"},
     {type:"gap_word",sentence:"A habit is formed when a behaviour is repeated and becomes ___.",options:["difficult","intentional","automatic","boring"],answer:2,explanation:"'it becomes automatic'"},
   ]},
  {id:"b1_2",level:"B1",title:"Urban Farming",topic:"Environment",
   passage:"As cities grow larger, some people are finding creative ways to grow food in urban areas. Rooftop gardens, vertical farms, and community allotments are becoming more common. Urban farming offers several benefits: it reduces the distance food travels, provides fresh produce to local communities, and helps people reconnect with nature. However, it also faces challenges such as limited space, high costs, and lack of sunlight in dense cities.",
   questions:[
     {type:"mcq",q:"Which is NOT listed as a challenge of urban farming?",options:["Limited space","High costs","Lack of sunlight","Water shortage"],answer:3,explanation:"Water shortage is not mentioned; the challenges listed are space, costs, and sunlight."},
     {type:"mcq",q:"What does urban farming reduce?",options:["Community connections","Food distance","City size","Costs"],answer:1,explanation:"'it reduces the distance food travels'"},
     {type:"gap_word",sentence:"Urban farming helps people reconnect with ___.",options:["technology","each other","nature","the city"],answer:2,explanation:"'helps people reconnect with nature'"},
   ]},
  {id:"b1_3",level:"B1",title:"Sleep and Memory",topic:"Science",
   passage:"Most people know that sleep is important for health, but fewer understand exactly why. During sleep, the brain is remarkably active. It processes and organises information gathered during the day, moving short-term memories into long-term storage. Research shows that students who sleep well after studying retain significantly more information than those who stay up late. Even a short nap of 20 minutes can improve focus and recall. Experts recommend 7 to 9 hours of sleep per night for adults.",
   questions:[
     {type:"mcq",q:"What does the brain do with short-term memories during sleep?",options:["Deletes them","Moves them to long-term storage","Creates new ones","Ignores them"],answer:1,explanation:"'moving short-term memories into long-term storage'"},
     {type:"mcq",q:"How long should a useful nap be according to the passage?",options:["5 minutes","10 minutes","20 minutes","45 minutes"],answer:2,explanation:"'a short nap of 20 minutes can improve focus'"},
     {type:"gap_word",sentence:"Experts recommend ___ to 9 hours of sleep for adults.",options:["5","6","7","8"],answer:2,explanation:"'7 to 9 hours of sleep per night for adults'"},
   ]},
  // ── B2 ──
  {id:"b2_1",level:"B2",title:"The Attention Economy",topic:"Technology",
   passage:"Social media platforms are designed to capture and hold your attention for as long as possible. Every notification, like, and scroll is engineered to trigger dopamine release, keeping users engaged. This business model — selling advertisers access to user attention — is called the attention economy. Critics argue that this design creates addictive behaviour patterns and fragments our ability to concentrate. Some researchers link heavy social media use to rising rates of anxiety and depression, particularly among teenagers. However, others maintain that correlation does not imply causation, and that the evidence remains inconclusive.",
   questions:[
     {type:"mcq",q:"What is the 'attention economy' as described in the passage?",options:["A system for managing time","Selling advertisers access to user attention","A type of social media platform","A psychological theory"],answer:1,explanation:"'selling advertisers access to user attention is called the attention economy'"},
     {type:"mcq",q:"What do critics say social media design creates?",options:["Community bonds","Addictive behaviour patterns","Better concentration","Healthier teenagers"],answer:1,explanation:"'this design creates addictive behaviour patterns and fragments our ability to concentrate'"},
     {type:"qa",q:"Why do some researchers disagree with the link between social media and mental health problems?",keywords:["correlation","causation","inconclusive","evidence"],explanation:"They argue that correlation does not imply causation, and the evidence is inconclusive."},
   ]},
  {id:"b2_2",level:"B2",title:"Rewilding",topic:"Environment",
   passage:"Rewilding is a conservation approach that aims to restore ecosystems to their natural state by reintroducing species that have disappeared. Unlike traditional conservation, which focuses on protecting what remains, rewilding seeks to rebuild natural processes. The reintroduction of wolves to Yellowstone National Park in the USA is often cited as a success story. The wolves reduced deer populations, which allowed vegetation to recover, which in turn stabilised riverbanks and changed waterflow. This cascade of effects is known as a 'trophic cascade.' Critics, however, warn that reintroducing predators near human settlements can create conflict.",
   questions:[
     {type:"mcq",q:"How does rewilding differ from traditional conservation?",options:["It focuses only on plants","It rebuilds natural processes rather than protecting remains","It relies on technology","It is cheaper"],answer:1,explanation:"'rewilding seeks to rebuild natural processes' vs protecting what remains."},
     {type:"mcq",q:"What is a 'trophic cascade'?",options:["A type of waterfall","A series of ecological effects triggered by one change","A reintroduction programme","A hunting technique"],answer:1,explanation:"The cascade of effects from wolf reintroduction is called a trophic cascade."},
     {type:"gap_word",sentence:"The reintroduction of wolves ___ deer populations.",options:["increased","stabilised","reduced","eliminated"],answer:2,explanation:"'The wolves reduced deer populations'"},
   ]},
  {id:"b2_3",level:"B2",title:"The Placebo Effect",topic:"Medicine",
   passage:"The placebo effect is one of medicine's most fascinating and least understood phenomena. When patients receive an inert treatment — a sugar pill or saline injection — and believe it to be real medication, many show genuine physiological improvements. Studies have recorded reduced pain, lower blood pressure, and even shrinking tumours in placebo recipients. The mechanism is not fully understood, but researchers believe it involves the release of endorphins and changes in neural activity. Ethical debates surround its use: if placebos work, should doctors prescribe them even if doing so involves deception?",
   questions:[
     {type:"mcq",q:"What is an 'inert treatment'?",options:["A strong painkiller","A natural remedy","A treatment with no active ingredient","A surgical procedure"],answer:2,explanation:"Inert means having no active ingredient — like a sugar pill."},
     {type:"mcq",q:"Which is NOT listed as a placebo effect observed in studies?",options:["Reduced pain","Lower blood pressure","Improved vision","Shrinking tumours"],answer:2,explanation:"Improved vision is not mentioned in the passage."},
     {type:"qa",q:"What ethical question does the passage raise about placebos?",keywords:["deception","doctors","prescribe","ethical"],explanation:"Should doctors prescribe placebos even if doing so involves deceiving patients?"},
   ]},
  // ── C1 ──
  {id:"c1_1",level:"C1",title:"The Language Instinct",topic:"Linguistics",
   passage:"The linguist Noam Chomsky proposed that humans are born with an innate capacity for language — a 'language acquisition device' hardwired into the brain. This theory sought to explain why children acquire language so rapidly and uniformly across cultures, despite minimal explicit instruction. Critics, however, point to the statistical learning hypothesis, which suggests that children learn language by detecting patterns in the input they receive. Recent neuroimaging studies have identified dedicated language circuits in the brain, lending partial support to Chomsky's view, though the debate between nativist and empiricist accounts of language acquisition remains unresolved.",
   questions:[
     {type:"mcq",q:"What is Chomsky's 'language acquisition device'?",options:["A teaching tool","An innate brain capacity for language","A statistical model","A type of grammar"],answer:1,explanation:"Chomsky proposed an innate brain capacity for language called the language acquisition device."},
     {type:"mcq",q:"What does the statistical learning hypothesis suggest?",options:["Language is innate","Children learn by detecting patterns in input","Brain circuits determine language","Grammar is universal"],answer:1,explanation:"'children learn language by detecting patterns in the input they receive'"},
     {type:"qa",q:"What evidence partially supports Chomsky's view?",keywords:["neuroimaging","circuits","brain","dedicated"],explanation:"Neuroimaging studies identified dedicated language circuits in the brain."},
   ]},
  {id:"c1_2",level:"C1",title:"The Anthropocene",topic:"Climate",
   passage:"Geologists have proposed naming our current epoch the Anthropocene — the age of human influence — to reflect the unprecedented scale of humanity's impact on the Earth's systems. Evidence for this designation includes the global dispersal of microplastics, radionuclides from nuclear testing, and the homogenisation of species assemblages. The proposal is scientifically contested: some argue the changes are insufficient to define a new epoch, while others suggest the Holocene — the epoch beginning after the last ice age — remains the appropriate designation. The debate underscores a deeper question about whether geological time should accommodate human timescales.",
   questions:[
     {type:"mcq",q:"What does 'Anthropocene' refer to?",options:["A prehistoric era","The age of human influence on Earth","A geological period before humans","A climate model"],answer:1,explanation:"'the age of human influence' — reflecting humanity's impact on Earth's systems."},
     {type:"mcq",q:"Which piece of evidence is NOT mentioned?",options:["Microplastics","Radionuclides","Rising sea temperatures","Homogenisation of species"],answer:2,explanation:"Rising sea temperatures are not listed among the evidence cited."},
     {type:"qa",q:"What deeper question does the Anthropocene debate raise?",keywords:["geological","time","human","timescales","accommodate"],explanation:"Whether geological time should accommodate human timescales."},
   ]},
  {id:"c1_3",level:"C1",title:"Confirmation Bias",topic:"Psychology",
   passage:"Confirmation bias is the tendency to search for, interpret, and recall information in a way that confirms one's pre-existing beliefs. It operates unconsciously and affects even highly educated individuals. In political discourse, it reinforces polarisation: people curate information environments that reflect their worldview, making genuine dialogue across ideological lines increasingly difficult. In science, it manifests as selective reporting of results that support a hypothesis while ignoring contradictory evidence — a practice known as p-hacking. Mitigating confirmation bias requires deliberate effort: seeking disconfirming evidence, engaging with opposing viewpoints, and employing structured analytical techniques.",
   questions:[
     {type:"mcq",q:"What is 'p-hacking' as described in the passage?",options:["Hacking computers to get data","Selecting results that support a hypothesis while ignoring contradictions","A statistical test","A type of confirmation bias in politics"],answer:1,explanation:"'selective reporting of results that support a hypothesis while ignoring contradictory evidence'"},
     {type:"mcq",q:"Which strategy is NOT suggested for mitigating confirmation bias?",options:["Seeking disconfirming evidence","Engaging opposing viewpoints","Avoiding all news","Structured analytical techniques"],answer:2,explanation:"Avoiding all news is not mentioned; the strategies are seeking disconfirming evidence, engaging viewpoints, and structured techniques."},
     {type:"qa",q:"How does confirmation bias affect political discourse?",keywords:["polarisation","curate","worldview","dialogue","ideological"],explanation:"It reinforces polarisation by making people curate information environments matching their worldview, hindering genuine dialogue."},
   ]},
  // ── C2 ──
  {id:"c2_1",level:"C2",title:"The Ship of Theseus",topic:"Philosophy",
   passage:"The Ship of Theseus is an ancient paradox that probes the nature of identity and persistence through change. If every plank of a ship is gradually replaced, at what point — if any — does it cease to be the same ship? Thomas Hobbes extended the puzzle: if the original planks are collected and reassembled, which vessel is the 'true' Ship of Theseus? Contemporary philosophers have mapped this paradox onto questions of personal identity — whether the self persists through total cellular replacement, amnesia, or radical personality change. Derek Parfit argued that identity is not what matters; psychological continuity and connectedness are what ground our practical concerns about the future.",
   questions:[
     {type:"mcq",q:"What was Hobbes's contribution to the Ship of Theseus paradox?",options:["He solved it","He asked which ship is the 'true' one if original parts are reassembled","He applied it to biology","He dismissed it as meaningless"],answer:1,explanation:"Hobbes asked: if the original planks are reassembled, which is the true ship?"},
     {type:"mcq",q:"What does Parfit argue matters instead of identity?",options:["Physical continuity","Legal status","Psychological continuity and connectedness","Memory alone"],answer:2,explanation:"'psychological continuity and connectedness are what ground our practical concerns'"},
     {type:"qa",q:"How have contemporary philosophers applied the Ship of Theseus paradox?",keywords:["personal identity","self","cellular","amnesia","personality","persists"],explanation:"They apply it to questions of personal identity — whether the self persists through cellular replacement, amnesia, or radical personality change."},
   ]},
  {id:"c2_2",level:"C2",title:"The Extended Mind",topic:"Cognitive Science",
   passage:"The philosopher Andy Clark and cognitive scientist David Chalmers proposed the 'extended mind' thesis in 1998, arguing that the mind is not confined to the skull. When external objects — notebooks, smartphones, or other people — become so reliably integrated into our cognitive processes that we would be cognitively impaired without them, those objects should be considered part of the mind. Critics object that this conflates the vehicle of thought with thought itself, and that genuine mental states must be intrinsic to the organism. The debate has practical implications for how we conceptualise cognitive enhancement, disability, and the ethics of memory modification.",
   questions:[
     {type:"mcq",q:"What is the 'extended mind' thesis?",options:["The mind expands with intelligence","The mind includes reliably integrated external objects","The brain has extended regions","Thinking occurs only in language"],answer:1,explanation:"External objects reliably integrated into cognition should be considered part of the mind."},
     {type:"mcq",q:"What is the main criticism of the extended mind thesis?",options:["It is too narrow","It conflates the vehicle of thought with thought itself","It ignores technology","It is empirically untestable"],answer:1,explanation:"Critics say it conflates the vehicle of thought with thought itself."},
     {type:"qa",q:"What practical issues does the extended mind debate raise?",keywords:["cognitive enhancement","disability","memory","modification","ethics"],explanation:"It raises issues for conceptualising cognitive enhancement, disability, and the ethics of memory modification."},
   ]},
  {id:"c2_3",level:"C2",title:"Epistemic Injustice",topic:"Philosophy",
   passage:"Miranda Fricker coined the term 'epistemic injustice' to describe wrongs done to individuals specifically in their capacity as knowers. She identifies two primary forms. The first, testimonial injustice, occurs when a speaker receives less credibility than they deserve due to prejudice — a Black witness being disbelieved in court, for instance. The second, hermeneutical injustice, arises when a gap in collective interpretive resources disadvantages a group — as when, before the concept of sexual harassment was named, victims had no framework to articulate their experiences. Both forms of injustice are self-concealing and compound existing social inequalities.",
   questions:[
     {type:"mcq",q:"What is 'testimonial injustice'?",options:["Lying under oath","Giving false testimony","Receiving less credibility due to prejudice","Refusing to testify"],answer:2,explanation:"'a speaker receives less credibility than they deserve due to prejudice'"},
     {type:"mcq",q:"What makes hermeneutical injustice distinct from testimonial injustice?",options:["It involves legal proceedings","It arises from a gap in collective interpretive resources","It affects only minority groups","It requires deliberate intent"],answer:1,explanation:"Hermeneutical injustice arises when a gap in collective interpretive resources disadvantages a group."},
     {type:"qa",q:"Why are both forms of epistemic injustice described as 'self-concealing'?",keywords:["self-concealing","compound","inequalities","framework","articulate","named"],explanation:"They are self-concealing because victims often lack the framework to name or articulate what is happening to them, making the injustice invisible and compounding existing inequalities."},
   ]},
  // ── Extended Stories (A1-C2: 6 per level) ──
  {id:"a1_4",level:"A1",title:"The Park",topic:"Recreation",passage:"I like to go to the park on weekends. The park is near my home. There are trees and flowers. I play with my friends. We run and play games. Sometimes we eat ice cream. The park is fun and quiet. Everyone enjoys the park.",questions:[{type:"mcq",q:"Where is the park?",options:["Far away","Near home","In the city","By the beach"],answer:1,explanation:"The passage says 'The park is near my home.'"},{type:"mcq",q:"What do children do in the park?",options:["Work","Sleep","Play games and run","Study"],answer:2,explanation:"'I play with my friends. We run and play games.'"},{type:"qa",q:"Why do people like the park?",keywords:["fun","quiet","enjoy","trees","flowers"],explanation:"The passage says it is 'fun and quiet' and 'Everyone enjoys the park.'"}]},
  {id:"a2_4",level:"A2",title:"The Hobby",topic:"Interests",passage:"My hobby is painting. I paint pictures on weekends. I use bright colours like blue, red, and yellow. My friends think my paintings are beautiful. I show my paintings to my family. They are very proud of me. Painting helps me relax and express my feelings. I want to paint all the time.",questions:[{type:"mcq",q:"What is the narrator's hobby?",options:["Reading","Painting","Dancing","Singing"],answer:1,explanation:"'My hobby is painting.'"},{type:"mcq",q:"When does the narrator paint?",options:["Every day","At work","On weekends","In the evening"],answer:2,explanation:"'I paint pictures on weekends.'"},{type:"qa",q:"What colors does the narrator use?",keywords:["blue","red","yellow","bright"],explanation:"The narrator uses 'bright colours like blue, red, and yellow.'"}]},
  {id:"b1_4",level:"B1",title:"Learning Languages",topic:"Education",passage:"Learning a second language is an exciting challenge. Many people decide to learn English, Spanish, or Mandarin. Different methods work for different people. Some prefer classroom instruction, while others learn through apps and online resources. Consistency is key to progress. Regular practice helps build vocabulary and grammar skills. Immersion in the language—through movies, music, and conversations—accelerates learning. Motivation and patience are essential for success.",questions:[{type:"mcq",q:"What languages are mentioned as popular choices to learn?",options:["English, Spanish, Mandarin","French, German, Italian","Russian, Polish, Czech","Greek, Turkish, Arabic"],answer:0,explanation:"'Many people decide to learn English, Spanish, or Mandarin.'"},{type:"mcq",q:"Which factor is described as 'key to progress'?",options:["Having a tutor","Consistency","Natural talent","Expensive courses"],answer:1,explanation:"'Consistency is key to progress.'"},{type:"qa",q:"What methods can accelerate language learning?",keywords:["immersion","movies","music","conversations"],explanation:"'Immersion in the language—through movies, music, and conversations—accelerates learning.'"}]},
  {id:"b2_4",level:"B2",title:"Digital Privacy",topic:"Technology",passage:"The digital age has transformed how we communicate, work, and live. However, it has also introduced new challenges regarding privacy. Tech companies collect vast amounts of user data for targeted advertising and algorithmic curation. Many users are unaware of the extent to which their information is tracked across platforms. Privacy policies are often lengthy and written in complex language that discourages reading. Regulations like GDPR attempt to protect personal information, yet enforcement remains inconsistent. Individuals should be proactive: use strong passwords, enable two-factor authentication, and review privacy settings regularly.",questions:[{type:"mcq",q:"Why do tech companies collect user data?",options:["For scientific research","For targeted advertising and curation","For government surveillance","For academic studies"],answer:1,explanation:"'Tech companies collect vast amounts of user data for targeted advertising and algorithmic curation.'"},{type:"mcq",q:"What is one issue with privacy policies?",options:["They are too short","They are complex and lengthy, discouraging reading","They are freely available","They protect all data"],answer:1,explanation:"'Privacy policies are often lengthy and written in complex language that discourages reading.'"},{type:"qa",q:"What are three ways individuals can protect their privacy?",keywords:["strong passwords","two-factor authentication","review","privacy settings"],explanation:"'use strong passwords, enable two-factor authentication, and review privacy settings regularly.'"}]},
  {id:"c1_4",level:"C1",title:"Cognitive Biases",topic:"Psychology",passage:"Cognitive biases are systematic patterns in how humans process information and make decisions. They arise from the brain's need to simplify complex environments through heuristics—mental shortcuts. Common examples include confirmation bias (seeking information that confirms existing beliefs), availability heuristic (overweighting accessible information), and anchoring (relying heavily on initial information). These biases are not character flaws but evolutionary adaptations that generally served humans well in ancestral environments. However, in modern contexts involving large datasets and probabilistic reasoning, they often lead to suboptimal decisions. Understanding one's biases is the first step toward mitigating their effects.",questions:[{type:"mcq",q:"What are cognitive biases primarily caused by?",options:["Lack of intelligence","The brain's need to simplify through heuristics","Emotional instability","Poor education"],answer:1,explanation:"'They arise from the brain's need to simplify complex environments through heuristics.'"},{type:"mcq",q:"Which bias involves relying heavily on initial information?",options:["Confirmation bias","Availability heuristic","Anchoring","Recency bias"],answer:2,explanation:"'anchoring (relying heavily on initial information)'"},{type:"qa",q:"Why were cognitive biases adaptive in ancestral environments?",keywords:["evolutionary","simplified","ancestral","served"],explanation:"The passage states biases 'are evolutionary adaptations that generally served humans well in ancestral environments.'"}]},
  {id:"c2_4",level:"C2",title:"Phenomenology",topic:"Philosophy",passage:"Phenomenology, as developed by Edmund Husserl, is the study of consciousness and subjective experience. It emphasizes the essential structures of experience—how objects appear to consciousness through intentionality. Rather than seeking objective truth independent of observers, phenomenology examines the structures through which meaning is constituted. Maurice Merleau-Ponty extended phenomenology by emphasizing embodiment: experience is always mediated through the body, not disembodied consciousness. Contemporary phenomenology engages with intersubjectivity—how shared meaning emerges through social interaction. Critics argue phenomenology lacks empirical rigor, yet proponents contend it clarifies foundational questions about consciousness that neuroscience alone cannot address.",questions:[{type:"mcq",q:"What is intentionality in phenomenology?",options:["Having a goal or purpose","How objects appear to consciousness","Being intentional in actions","A logical principle"],answer:1,explanation:"'how objects appear to consciousness through intentionality.'"},{type:"mcq",q:"How did Merleau-Ponty extend Husserl's phenomenology?",options:["By adding mathematics","By emphasizing embodiment and the body's role","By rejecting consciousness","By using scientific methods"],answer:1,explanation:"'Maurice Merleau-Ponty extended phenomenology by emphasizing embodiment.'"},{type:"qa",q:"What criticism is leveled against phenomenology, and how do proponents respond?",keywords:["empirical rigor","consciousness","neuroscience","foundational questions"],explanation:"Critics argue it 'lacks empirical rigor,' yet proponents contend 'it clarifies foundational questions about consciousness that neuroscience alone cannot address.'"}]},

  // ── A1 extra ──
  {id:"a1_5",level:"A1",title:"My Bedroom",topic:"Home",passage:"My bedroom is small but nice. I have a bed, a desk, and a chair. My desk is by the window. I do my homework at my desk. My bed is soft and warm. I sleep very well at night. I have some books on a shelf. I also have a toy box. I love my bedroom very much.",questions:[{type:"mcq",q:"Where is the desk?",options:["By the door","By the window","In the kitchen","In the garden"],answer:1,explanation:"'My desk is by the window.'"},{type:"mcq",q:"What does the narrator do at the desk?",options:["Sleep","Cook","Do homework","Watch TV"],answer:2,explanation:"'I do my homework at my desk.'"},{type:"gap_word",sentence:"The narrator keeps books on a ___.",options:["table","shelf","bed","chair"],answer:1,explanation:"'I have some books on a shelf.'"}]},
  {id:"a1_6",level:"A1",title:"The Weather",topic:"Nature",passage:"Today the weather is sunny. The sky is blue and there are no clouds. It is warm but not hot. I put on a T-shirt and shorts. My mother opens the windows. We go for a walk in the garden. The flowers look beautiful in the sunshine. I am very happy today.",questions:[{type:"mcq",q:"What is the weather like today?",options:["Rainy","Cloudy","Sunny","Cold"],answer:2,explanation:"'Today the weather is sunny.'"},{type:"mcq",q:"What does the narrator wear?",options:["A coat and boots","A jacket and trousers","A T-shirt and shorts","A jumper and jeans"],answer:2,explanation:"'I put on a T-shirt and shorts.'"},{type:"gap_word",sentence:"The flowers look beautiful in the ___.",options:["rain","wind","snow","sunshine"],answer:3,explanation:"'The flowers look beautiful in the sunshine.'"}]},
  {id:"a1_7",level:"A1",title:"Breakfast Time",topic:"Food",passage:"Every morning I eat breakfast at seven o'clock. I have bread, butter, and a glass of milk. Sometimes I eat an egg. My mother makes breakfast for the family. We all sit at the table. My father drinks coffee. My sister eats cereal. Breakfast is my favourite meal of the day.",questions:[{type:"mcq",q:"What time does the narrator eat breakfast?",options:["Six o'clock","Seven o'clock","Eight o'clock","Nine o'clock"],answer:1,explanation:"'I eat breakfast at seven o'clock.'"},{type:"mcq",q:"What does the narrator's father drink?",options:["Milk","Tea","Juice","Coffee"],answer:3,explanation:"'My father drinks coffee.'"},{type:"gap_word",sentence:"Breakfast is the narrator's favourite ___ of the day.",options:["drink","sport","meal","book"],answer:2,explanation:"'Breakfast is my favourite meal of the day.'"}]},
  {id:"a1_8",level:"A1",title:"My Pet",topic:"Animals",passage:"I have a cat. Her name is Mimi. Mimi is white and orange. She is very soft. I feed her every morning. She likes fish and milk. Mimi sleeps on the sofa all day. At night she sleeps in my room. I love Mimi. She is my best friend.",questions:[{type:"mcq",q:"What colour is Mimi?",options:["Black and white","Orange and grey","White and orange","Brown and black"],answer:2,explanation:"'Mimi is white and orange.'"},{type:"mcq",q:"What does Mimi like to eat?",options:["Vegetables and bread","Fish and milk","Rice and meat","Fruit and cheese"],answer:1,explanation:"'She likes fish and milk.'"},{type:"gap_word",sentence:"Mimi sleeps on the sofa all ___.",options:["night","morning","day","week"],answer:2,explanation:"'Mimi sleeps on the sofa all day.'"}]},
  {id:"a1_9",level:"A1",title:"A Birthday Party",topic:"Celebrations",passage:"Today is my birthday. I am seven years old. My mother makes a big cake. The cake is chocolate. My friends come to my house. We play games and sing songs. My friend gives me a toy car. I am very happy. We eat cake and drink juice. It is a great day!",questions:[{type:"mcq",q:"How old is the narrator today?",options:["Five","Six","Seven","Eight"],answer:2,explanation:"'I am seven years old.'"},{type:"mcq",q:"What kind of cake does the mother make?",options:["Vanilla","Strawberry","Lemon","Chocolate"],answer:3,explanation:"'The cake is chocolate.'"},{type:"gap_word",sentence:"The narrator's friend gives a toy ___.",options:["boat","car","plane","train"],answer:1,explanation:"'My friend gives me a toy car.'"}]},
  {id:"a1_10",level:"A1",title:"The Seasons",topic:"Nature",passage:"There are four seasons in a year. They are spring, summer, autumn, and winter. In spring the flowers grow. In summer it is hot and sunny. In autumn the leaves fall from the trees. In winter it is cold and sometimes it snows. I like summer because I can swim. What is your favourite season?",questions:[{type:"mcq",q:"How many seasons are there in a year?",options:["Two","Three","Four","Five"],answer:2,explanation:"'There are four seasons in a year.'"},{type:"mcq",q:"What happens in autumn?",options:["Flowers grow","It snows","Leaves fall","It is hot"],answer:2,explanation:"'In autumn the leaves fall from the trees.'"},{type:"gap_word",sentence:"In winter it is cold and sometimes it ___.",options:["rains","snows","shines","floods"],answer:1,explanation:"'In winter it is cold and sometimes it snows.'"}]},

  // ── A2 extra ──
  {id:"a2_5",level:"A2",title:"A Trip to the Zoo",topic:"Animals",passage:"Last Sunday, my family went to the zoo. We saw many animals — lions, elephants, and giraffes. The giraffes were my favourite because they were so tall. We also watched a dolphin show. The dolphins jumped high out of the water. After the show, we ate sandwiches in the park. It was a wonderful day. I want to go back next year.",questions:[{type:"mcq",q:"When did the family visit the zoo?",options:["Saturday","Sunday","Monday","Friday"],answer:1,explanation:"'Last Sunday, my family went to the zoo.'"},{type:"mcq",q:"Why did the narrator like the giraffes?",options:["They were colourful","They were very fast","They were so tall","They were friendly"],answer:2,explanation:"'The giraffes were my favourite because they were so tall.'"},{type:"gap_word",sentence:"After the dolphin show, the family ate ___ in the park.",options:["pizza","cake","sandwiches","ice cream"],answer:2,explanation:"'we ate sandwiches in the park.'"}]},
  {id:"a2_6",level:"A2",title:"Learning to Ride a Bike",topic:"Sport",passage:"When I was six, my father taught me to ride a bike. It was very difficult at first. I fell down many times. But my father always helped me. He held the bike and ran beside me. After one week of practice, I could ride alone. I was so proud of myself. Now I cycle to school every day. It is my favourite way to travel.",questions:[{type:"mcq",q:"Who taught the narrator to ride a bike?",options:["Mother","Brother","Father","Teacher"],answer:2,explanation:"'my father taught me to ride a bike.'"},{type:"mcq",q:"How long did it take to learn to ride alone?",options:["One day","Three days","One week","One month"],answer:2,explanation:"'After one week of practice, I could ride alone.'"},{type:"gap_word",sentence:"Now the narrator cycles to school every ___.",options:["week","month","weekend","day"],answer:3,explanation:"'Now I cycle to school every day.'"}]},
  {id:"a2_7",level:"A2",title:"The Library",topic:"Education",passage:"There is a big library in my town. I go there every Saturday. The library has thousands of books. I love reading adventure stories. I can also borrow DVDs and magazines. The librarian is very kind. She always helps me find the right book. I can stay in the library for hours. Reading makes me feel happy and calm.",questions:[{type:"mcq",q:"When does the narrator visit the library?",options:["Every Sunday","Every Saturday","Every Friday","Every Monday"],answer:1,explanation:"'I go there every Saturday.'"},{type:"mcq",q:"What kind of books does the narrator love?",options:["Science books","History books","Adventure stories","Cookery books"],answer:2,explanation:"'I love reading adventure stories.'"},{type:"gap_word",sentence:"Reading makes the narrator feel happy and ___.",options:["tired","bored","calm","excited"],answer:2,explanation:"'Reading makes me feel happy and calm.'"}]},
  {id:"a2_8",level:"A2",title:"A Rainy Day",topic:"Daily Life",passage:"Yesterday it rained all day. I could not go outside. In the morning I read a book and listened to music. In the afternoon my sister and I played board games. We laughed a lot. My mother made soup for lunch. It was warm and delicious. By evening the rain stopped. I went outside and saw a beautiful rainbow. It was a lovely surprise.",questions:[{type:"mcq",q:"What did the narrator do in the morning?",options:["Watched TV and played games","Read a book and listened to music","Slept and ate breakfast","Cooked and cleaned"],answer:1,explanation:"'In the morning I read a book and listened to music.'"},{type:"mcq",q:"What did the narrator see in the evening?",options:["Clouds","Stars","A rainbow","Lightning"],answer:2,explanation:"'I went outside and saw a beautiful rainbow.'"},{type:"gap_word",sentence:"The narrator's mother made ___ for lunch.",options:["pizza","soup","rice","pasta"],answer:1,explanation:"'My mother made soup for lunch.'"}]},
  {id:"a2_9",level:"A2",title:"My Favourite Food",topic:"Food",passage:"My favourite food is pizza. I eat it every Friday with my family. We order pizza from a restaurant near our house. I like pizza with cheese and vegetables. My brother prefers pizza with meat. We always share a big pizza together. My mother makes a salad. We drink juice or water. Friday dinner is my favourite time of the week.",questions:[{type:"mcq",q:"When does the family eat pizza?",options:["Every Monday","Every Wednesday","Every Friday","Every Sunday"],answer:2,explanation:"'I eat it every Friday with my family.'"},{type:"mcq",q:"What topping does the narrator prefer?",options:["Meat","Fish","Cheese and vegetables","Onions"],answer:2,explanation:"'I like pizza with cheese and vegetables.'"},{type:"gap_word",sentence:"The family orders pizza from a restaurant ___ their house.",options:["far from","inside","near","behind"],answer:2,explanation:"'We order pizza from a restaurant near our house.'"}]},
  {id:"a2_10",level:"A2",title:"A New Friend",topic:"School",passage:"Last month, a new student joined our class. Her name is Sofia. She moved from another city. At first, Sofia was very quiet and shy. I sat next to her and showed her around the school. We had lunch together every day. Soon she started smiling and talking more. Now Sofia is one of my best friends. I am glad I helped her.",questions:[{type:"mcq",q:"How was Sofia when she first arrived?",options:["Loud and confident","Quiet and shy","Rude and unfriendly","Happy and talkative"],answer:1,explanation:"'At first, Sofia was very quiet and shy.'"},{type:"mcq",q:"What did the narrator do to help Sofia?",options:["Bought her lunch","Showed her around and had lunch with her","Introduced her to the teacher","Did homework with her"],answer:1,explanation:"'I sat next to her and showed her around the school. We had lunch together every day.'"},{type:"gap_word",sentence:"Now Sofia is one of the narrator's best ___.",options:["teachers","neighbours","friends","cousins"],answer:2,explanation:"'Now Sofia is one of my best friends.'"}]},

  // ── B1 extra ──
  {id:"b1_5",level:"B1",title:"Social Media and Teenagers",topic:"Technology",passage:"Social media platforms are used by millions of teenagers worldwide. Apps like Instagram, TikTok, and Snapchat allow young people to share photos, videos, and messages instantly. Many teenagers say social media helps them stay connected with friends and discover new interests. However, experts warn that excessive use can reduce focus and sleep quality. Comparing oneself to others online can also lower self-confidence. Parents and educators encourage young people to set time limits and take regular breaks from screens.",questions:[{type:"mcq",q:"What do experts warn about excessive social media use?",options:["It improves focus","It can reduce focus and sleep quality","It increases self-confidence","It helps with studying"],answer:1,explanation:"'experts warn that excessive use can reduce focus and sleep quality.'"},{type:"mcq",q:"What do parents and educators encourage teenagers to do?",options:["Stop using social media","Use only educational apps","Set time limits and take breaks","Post more content"],answer:2,explanation:"'Parents and educators encourage young people to set time limits and take regular breaks.'"},{type:"gap_word",sentence:"Comparing oneself to others online can lower ___.",options:["grades","weight","self-confidence","income"],answer:2,explanation:"'Comparing oneself to others online can also lower self-confidence.'"}]},
  {id:"b1_6",level:"B1",title:"Volunteering",topic:"Community",passage:"Volunteering means giving your time and skills to help others without being paid. Many people volunteer at hospitals, animal shelters, food banks, and community centres. Volunteers do tasks such as serving meals, caring for animals, teaching literacy classes, and supporting elderly people. Studies show that volunteering benefits not only the community but also the volunteers themselves. People who volunteer regularly report higher levels of happiness and a greater sense of purpose. Even a few hours a month can make a real difference.",questions:[{type:"mcq",q:"What is volunteering?",options:["Working for a high salary","Giving time to help others without pay","Starting a business","Teaching at a university"],answer:1,explanation:"'Volunteering means giving your time and skills to help others without being paid.'"},{type:"mcq",q:"According to studies, how do volunteers benefit?",options:["They earn more money","They get promoted faster","They report higher happiness and purpose","They become healthier physically"],answer:2,explanation:"'People who volunteer regularly report higher levels of happiness and a greater sense of purpose.'"},{type:"gap_word",sentence:"Even a few hours a month can make a real ___.",options:["mistake","delay","difference","profit"],answer:2,explanation:"'Even a few hours a month can make a real difference.'"}]},
  {id:"b1_7",level:"B1",title:"Healthy Eating",topic:"Health",passage:"Eating a balanced diet is one of the most important things you can do for your health. A healthy diet includes plenty of fruits and vegetables, whole grains, protein from meat or plant sources, and limited amounts of sugar and saturated fat. Eating well provides energy, improves concentration, and reduces the risk of diseases like diabetes and heart disease. However, healthy eating does not need to be expensive. Cooking meals at home, buying seasonal vegetables, and reducing takeaways are practical steps anyone can take.",questions:[{type:"mcq",q:"What does a balanced diet include?",options:["Mainly meat and dairy","Fruits, vegetables, whole grains, and protein","Only raw foods","Mostly carbohydrates"],answer:1,explanation:"'A healthy diet includes plenty of fruits and vegetables, whole grains, protein... and limited amounts of sugar and saturated fat.'"},{type:"mcq",q:"Which disease is NOT mentioned as reduced by healthy eating?",options:["Diabetes","Heart disease","Obesity","Cancer"],answer:3,explanation:"The passage mentions diabetes and heart disease but not cancer."},{type:"gap_word",sentence:"Cooking meals at home and buying ___ vegetables are practical steps.",options:["organic","seasonal","imported","frozen"],answer:1,explanation:"'buying seasonal vegetables...are practical steps anyone can take.'"}]},
  {id:"b1_8",level:"B1",title:"The History of Music",topic:"Culture",passage:"Music has existed in every human culture throughout history. The earliest instruments, such as flutes made from bone, date back over 40,000 years. In ancient civilisations, music was closely connected to religion, festivals, and storytelling. The invention of music notation in medieval Europe allowed compositions to be written down and shared. The industrial revolution led to mass production of instruments and eventually to recorded music in the twentieth century. Today, digital technology means anyone can record and share music globally within seconds.",questions:[{type:"mcq",q:"How old are the earliest known musical instruments?",options:["10,000 years","20,000 years","Over 40,000 years","100,000 years"],answer:2,explanation:"'The earliest instruments...date back over 40,000 years.'"},{type:"mcq",q:"What did music notation allow?",options:["Faster performance","Mass production of instruments","Compositions to be written down and shared","Digital recording"],answer:2,explanation:"'music notation...allowed compositions to be written down and shared.'"},{type:"gap_word",sentence:"In ancient civilisations, music was connected to religion, festivals, and ___.",options:["commerce","warfare","storytelling","architecture"],answer:2,explanation:"'music was closely connected to religion, festivals, and storytelling.'"}]},
  {id:"b1_9",level:"B1",title:"City Living vs Rural Life",topic:"Society",passage:"People around the world live either in cities or in the countryside, and both lifestyles have advantages and disadvantages. City life offers better job opportunities, access to services, and entertainment. However, cities can be noisy, expensive, and stressful. Rural life provides fresh air, open space, and a sense of community, but can be isolated and have fewer job options. In recent years, remote working has allowed some people to enjoy the best of both worlds — working for city companies while living in quieter areas.",questions:[{type:"mcq",q:"What is one disadvantage of city life mentioned?",options:["Lack of jobs","Limited entertainment","Noise and high costs","No internet access"],answer:2,explanation:"'cities can be noisy, expensive, and stressful.'"},{type:"mcq",q:"How has remote working changed things for some people?",options:["It has made cities less popular","It allows people to enjoy benefits of both city and rural life","It has increased rural poverty","It has eliminated offices"],answer:1,explanation:"'remote working has allowed some people to enjoy the best of both worlds.'"},{type:"gap_word",sentence:"Rural life provides fresh air, open space, and a sense of ___.",options:["fashion","community","ambition","competition"],answer:1,explanation:"'Rural life provides fresh air, open space, and a sense of community.'"}]},
  {id:"b1_10",level:"B1",title:"Water on Earth",topic:"Science",passage:"Water covers about 71 percent of the Earth's surface, yet only about 3 percent of all water is fresh and suitable for drinking. Most of this fresh water is frozen in glaciers and polar ice caps. Less than one percent is easily accessible in rivers, lakes, and groundwater. Access to clean water is a serious global challenge. In many developing countries, people must walk kilometres to collect water, which is often contaminated. Climate change is making water shortages worse by altering rainfall patterns and melting glaciers faster than before.",questions:[{type:"mcq",q:"What percentage of Earth's water is fresh?",options:["71 percent","50 percent","About 3 percent","10 percent"],answer:2,explanation:"'only about 3 percent of all water is fresh and suitable for drinking.'"},{type:"mcq",q:"Where is most of Earth's fresh water?",options:["In rivers and lakes","In clouds","In oceans","Frozen in glaciers and polar ice caps"],answer:3,explanation:"'Most of this fresh water is frozen in glaciers and polar ice caps.'"},{type:"gap_word",sentence:"Climate change is making water shortages worse by altering ___ patterns.",options:["traffic","rainfall","farming","trade"],answer:1,explanation:"'Climate change is making water shortages worse by altering rainfall patterns.'"}]},

  // ── B2 extra ──
  {id:"b2_5",level:"B2",title:"The Gig Economy",topic:"Economics",passage:"The gig economy refers to a labour market characterised by short-term contracts and freelance work rather than permanent employment. Platforms such as Uber, Deliveroo, and Upwork have made it easy for workers to find temporary tasks. Proponents argue that gig work offers flexibility and autonomy, allowing people to set their own hours and take on multiple clients. Critics, however, point out that gig workers typically lack job security, employee benefits such as sick pay and pensions, and stable income. The debate raises fundamental questions about how labour rights should adapt to modern digital economies.",questions:[{type:"mcq",q:"What characterises the gig economy?",options:["Long-term contracts and high salaries","Short-term contracts and freelance work","Government employment programmes","Trade union agreements"],answer:1,explanation:"'The gig economy refers to a labour market characterised by short-term contracts and freelance work.'"},{type:"mcq",q:"What do critics highlight as a weakness of gig work?",options:["Too much flexibility","Lack of security and benefits","High wages","Too many clients"],answer:1,explanation:"'gig workers typically lack job security, employee benefits...and stable income.'"},{type:"qa",q:"What fundamental question does the gig economy raise?",keywords:["labour rights","digital","adapt","modern"],explanation:"It raises 'fundamental questions about how labour rights should adapt to modern digital economies.'"}]},
  {id:"b2_6",level:"B2",title:"Architecture and Society",topic:"Culture",passage:"Architecture is far more than the design of buildings — it shapes how people feel, interact, and live. Throughout history, architectural style has reflected the values and ambitions of each era. Ancient Egyptian pyramids symbolised power and the afterlife. Gothic cathedrals embodied spiritual aspiration. Modernist glass towers celebrate efficiency and rationalism. Contemporary architects increasingly focus on sustainability, designing buildings that consume less energy, incorporate green spaces, and use recycled materials. Urban planners argue that thoughtful design can reduce crime, increase happiness, and foster a sense of community.",questions:[{type:"mcq",q:"What did Gothic cathedrals embody?",options:["Commercial success","Political power","Military strength","Spiritual aspiration"],answer:3,explanation:"'Gothic cathedrals embodied spiritual aspiration.'"},{type:"mcq",q:"What do contemporary architects increasingly focus on?",options:["Greater height","Historical recreation","Sustainability and energy efficiency","Luxury materials"],answer:2,explanation:"'Contemporary architects increasingly focus on sustainability, designing buildings that consume less energy.'"},{type:"qa",q:"According to urban planners, how can thoughtful design benefit society?",keywords:["crime","happiness","community","design"],explanation:"'thoughtful design can reduce crime, increase happiness, and foster a sense of community.'"}]},
  {id:"b2_7",level:"B2",title:"Memory and Learning",topic:"Psychology",passage:"Memory is not a single system but a collection of distinct processes. Working memory holds information temporarily for immediate use, while long-term memory stores knowledge for extended periods. Research shows that the most effective learning strategies involve active retrieval — testing yourself rather than simply re-reading. The spacing effect demonstrates that spreading study sessions over time produces better retention than cramming. Emotional experiences are often remembered more vividly because the amygdala enhances encoding when arousal is high. Understanding these mechanisms helps students adopt evidence-based study techniques.",questions:[{type:"mcq",q:"What is the most effective learning strategy according to research?",options:["Re-reading notes","Listening to lectures","Active retrieval — testing yourself","Using colour-coded notes"],answer:2,explanation:"'the most effective learning strategies involve active retrieval — testing yourself rather than simply re-reading.'"},{type:"mcq",q:"What does the spacing effect show?",options:["Cramming is most effective","Short revision is enough","Spreading sessions over time improves retention","Working memory is unlimited"],answer:2,explanation:"'The spacing effect demonstrates that spreading study sessions over time produces better retention than cramming.'"},{type:"qa",q:"Why are emotional experiences often remembered more vividly?",keywords:["amygdala","arousal","encoding","emotional"],explanation:"'the amygdala enhances encoding when arousal is high.'"}]},
  {id:"b2_8",level:"B2",title:"Globalisation and Culture",topic:"Society",passage:"Globalisation has accelerated the flow of goods, ideas, and people across borders. While it has brought economic growth and raised living standards in many regions, it has also sparked debates about cultural homogenisation. Critics argue that dominant global cultures — particularly American popular culture — are eroding local traditions, languages, and identities. However, many scholars counter that cultures are not passive recipients. Local communities adapt imported ideas, creating hybrid forms that blend global and traditional elements. This process, known as glocalisation, suggests that cultural identity can be both resilient and dynamic.",questions:[{type:"mcq",q:"What do critics fear globalisation is doing to local cultures?",options:["Strengthening them","Eroding traditions and identities","Making them wealthier","Spreading them globally"],answer:1,explanation:"'dominant global cultures...are eroding local traditions, languages, and identities.'"},{type:"mcq",q:"What is 'glocalisation'?",options:["Moving businesses overseas","The decline of local culture","Blending global and traditional cultural elements","A form of economic protectionism"],answer:2,explanation:"'Local communities adapt imported ideas, creating hybrid forms that blend global and traditional elements. This process...is glocalisation.'"},{type:"qa",q:"How do scholars argue that cultures respond to globalisation?",keywords:["adapt","hybrid","resilient","dynamic","glocalisation"],explanation:"'cultures are not passive recipients. Local communities adapt imported ideas, creating hybrid forms' — a process called glocalisation."}]},
  {id:"b2_9",level:"B2",title:"Artificial Intelligence in Everyday Life",topic:"Technology",passage:"Artificial intelligence is no longer confined to research laboratories — it is embedded in the tools billions of people use daily. Recommendation algorithms curate the music, videos, and news we consume. Natural language processing powers virtual assistants and translation apps. Machine learning models detect fraud in banking and diagnose diseases in radiology. While these applications deliver genuine convenience, they raise important concerns. Opaque algorithms can encode and amplify societal biases. Over-reliance on AI decision-making may erode human accountability. The challenge for society is to harness AI's benefits while establishing robust governance frameworks.",questions:[{type:"mcq",q:"What do recommendation algorithms do?",options:["Write code automatically","Translate languages","Curate music, videos, and news","Detect bank fraud"],answer:2,explanation:"'Recommendation algorithms curate the music, videos, and news we consume.'"},{type:"mcq",q:"What concern does the passage raise about AI algorithms?",options:["They are too slow","They can encode and amplify societal biases","They consume too much power","They are not widely available"],answer:1,explanation:"'Opaque algorithms can encode and amplify societal biases.'"},{type:"qa",q:"What does the passage identify as the key challenge for society regarding AI?",keywords:["harness","benefits","governance","accountability"],explanation:"'The challenge for society is to harness AI's benefits while establishing robust governance frameworks.'"}]},
  {id:"b2_10",level:"B2",title:"Ocean Ecosystems",topic:"Science",passage:"The world's oceans cover over 70 percent of Earth's surface and contain the most diverse ecosystems on the planet. Coral reefs, often called the rainforests of the sea, support approximately 25 percent of all marine species despite covering less than one percent of the ocean floor. Deep-sea ecosystems remain largely unexplored; creatures at extreme depths survive without sunlight through chemosynthesis. The oceans play a crucial role in regulating the global climate by absorbing carbon dioxide and distributing heat. However, rising sea temperatures, ocean acidification, and plastic pollution are threatening marine biodiversity at an unprecedented rate.",questions:[{type:"mcq",q:"Why are coral reefs compared to rainforests?",options:["They are found in tropical areas","They are large and green","They support a huge proportion of species despite small size","They produce oxygen"],answer:2,explanation:"'Coral reefs...support approximately 25 percent of all marine species despite covering less than one percent of the ocean floor.'"},{type:"mcq",q:"How do deep-sea creatures survive without sunlight?",options:["Using stored nutrients","Through photosynthesis","Through bioluminescence","Through chemosynthesis"],answer:3,explanation:"'creatures at extreme depths survive without sunlight through chemosynthesis.'"},{type:"qa",q:"What role do oceans play in regulating the global climate?",keywords:["carbon dioxide","absorbing","heat","distributing"],explanation:"'The oceans play a crucial role in regulating the global climate by absorbing carbon dioxide and distributing heat.'"}]},

  // ── C1 extra ──
  {id:"c1_5",level:"C1",title:"The Ethics of Artificial Intelligence",topic:"Ethics",passage:"As artificial intelligence systems become increasingly capable of autonomous decision-making, profound ethical questions emerge. One central concern is moral responsibility: when an AI causes harm — such as a self-driving vehicle fatally striking a pedestrian — who bears accountability? The developer, the manufacturer, or the operator? Philosophers have proposed various frameworks, from strict liability models to distributed responsibility schemes. A second concern involves algorithmic fairness: training data reflecting historical inequalities can produce models that systematically disadvantage marginalised groups. Addressing these challenges requires not only technical solutions but also governance structures that embed ethical principles into the design, deployment, and auditing of AI systems.",questions:[{type:"mcq",q:"What is the central concern about moral responsibility in AI?",options:["AI systems being too slow","Unclear accountability when AI causes harm","High costs of AI development","AI replacing all jobs"],answer:1,explanation:"'when an AI causes harm...who bears accountability? The developer, the manufacturer, or the operator?'"},{type:"mcq",q:"How does algorithmic fairness become a problem?",options:["AI systems are programmed to discriminate","Training data reflecting historical inequalities disadvantages marginalised groups","Algorithms are too complex to audit","AI has no access to historical data"],answer:1,explanation:"'training data reflecting historical inequalities can produce models that systematically disadvantage marginalised groups.'"},{type:"qa",q:"What dual approach does the passage suggest for addressing AI ethics challenges?",keywords:["technical","governance","ethical","design","auditing"],explanation:"It requires 'not only technical solutions but also governance structures that embed ethical principles into the design, deployment, and auditing of AI systems.'"}]},
  {id:"c1_6",level:"C1",title:"Narrative and Identity",topic:"Literature",passage:"Contemporary literary theorists argue that human identity is fundamentally narrative in structure. We understand ourselves by constructing stories — selecting events, imposing causality, and projecting forward to an anticipated future. Paul Ricoeur's concept of 'narrative identity' holds that the self is neither a fixed substance nor a mere illusion, but an ongoing interpretive achievement mediated through storytelling. This perspective has significant implications for psychology and therapy: autobiographical narratives can be revised, enabling people to reconstitute their identities following trauma. However, critics caution that narrative coherence can be deceptive — imposing false unity on inherently fragmented experience.",questions:[{type:"mcq",q:"What does Paul Ricoeur mean by 'narrative identity'?",options:["The self is fixed and unchanging","Identity is constructed through ongoing storytelling","People's identities are determined by others","The self is a complete illusion"],answer:1,explanation:"'the self is...an ongoing interpretive achievement mediated through storytelling.'"},{type:"mcq",q:"What therapeutic implication does narrative identity have?",options:["Trauma is irreversible","People cannot change their self-perception","Autobiographical narratives can be revised to reconstitute identity","All memories must be suppressed"],answer:2,explanation:"'autobiographical narratives can be revised, enabling people to reconstitute their identities following trauma.'"},{type:"qa",q:"What criticism is raised against narrative identity theory?",keywords:["coherence","deceptive","fragmented","false unity"],explanation:"'narrative coherence can be deceptive — imposing false unity on inherently fragmented experience.'"}]},
  {id:"c1_7",level:"C1",title:"Behavioural Economics",topic:"Economics",passage:"Classical economics assumed that human beings are rational actors who consistently maximise utility. Behavioural economics, drawing on insights from psychology, challenges this premise. Research by Kahneman and Tversky demonstrated systematic irrationalities: loss aversion (losses feel roughly twice as painful as equivalent gains), the framing effect (decisions change depending on how options are presented), and the sunk cost fallacy (continuing to invest in a failing project because of past expenditure). These findings have practical applications in public policy — 'nudge' theory uses default options and choice architecture to guide people towards beneficial behaviours without coercion.",questions:[{type:"mcq",q:"What assumption does classical economics make?",options:["People are irrational and emotional","Human beings are rational utility-maximisers","People always choose the cheapest option","Governments control economic decisions"],answer:1,explanation:"'Classical economics assumed that human beings are rational actors who consistently maximise utility.'"},{type:"mcq",q:"What is loss aversion?",options:["Refusing to invest","Losses feeling roughly twice as painful as equivalent gains","Preferring small gains to large ones","The tendency to lose money in gambling"],answer:1,explanation:"'loss aversion (losses feel roughly twice as painful as equivalent gains)'"},{type:"qa",q:"How does nudge theory apply behavioural economics to public policy?",keywords:["default","choice architecture","beneficial","coercion","guide"],explanation:"'nudge theory uses default options and choice architecture to guide people towards beneficial behaviours without coercion.'"}]},
  {id:"c1_8",level:"C1",title:"Climate Tipping Points",topic:"Science",passage:"Climate scientists warn that Earth's systems contain tipping points — thresholds beyond which self-reinforcing feedback loops drive change irreversibly. The melting of Arctic permafrost releases methane, a potent greenhouse gas, which accelerates further warming. The loss of Greenland's ice sheet would raise sea levels by approximately seven metres over centuries. Deforestation in the Amazon could transform that ecosystem from a carbon sink into a carbon source. What makes tipping points particularly dangerous is their non-linear nature: gradual change can suddenly trigger rapid, cascading consequences. Some researchers argue that multiple tipping points may interact, creating compound effects that exceed the sum of individual changes.",questions:[{type:"mcq",q:"What makes tipping points particularly dangerous?",options:["They are very common","Their linear and predictable nature","Their non-linear nature — gradual change can trigger rapid consequences","They can be easily reversed"],answer:2,explanation:"'What makes tipping points particularly dangerous is their non-linear nature: gradual change can suddenly trigger rapid, cascading consequences.'"},{type:"mcq",q:"What would the loss of Greenland's ice sheet cause?",options:["A new ice age","Sea level rise of approximately seven metres","Collapse of the Amazon","Global cooling"],answer:1,explanation:"'The loss of Greenland's ice sheet would raise sea levels by approximately seven metres over centuries.'"},{type:"qa",q:"Why might multiple tipping points interacting be especially concerning?",keywords:["compound","cascading","exceed","interact","sum"],explanation:"'multiple tipping points may interact, creating compound effects that exceed the sum of individual changes.'"}]},
  {id:"c1_9",level:"C1",title:"Post-Colonial Identity",topic:"History",passage:"Post-colonial theory examines the lasting cultural, psychological, and political legacies of colonialism. Frantz Fanon argued that colonial rule damaged not only the material conditions of colonised peoples but their sense of self — a process he termed 'psychic alienation.' The colonised were compelled to internalise the coloniser's language, values, and history, effectively erasing indigenous identity. Homi Bhabha introduced the concept of 'hybridity' — the idea that colonised subjects do not simply replicate or reject colonial culture, but produce something new at the border between cultures. This hybrid space, he argued, is a site of both ambivalence and creative resistance.",questions:[{type:"mcq",q:"What did Fanon mean by 'psychic alienation'?",options:["Physical displacement","Economic poverty caused by colonialism","The psychological damage of internalising the coloniser's values","Political exile"],answer:2,explanation:"'colonial rule damaged...their sense of self — a process he termed psychic alienation.'"},{type:"mcq",q:"What is Bhabha's concept of 'hybridity'?",options:["The mixing of languages only","The complete adoption of colonial culture","A new cultural form produced at the border between cultures","The rejection of all colonial influence"],answer:2,explanation:"'colonised subjects...produce something new at the border between cultures.'  This is hybridity."},{type:"qa",q:"What does Bhabha argue about the hybrid space between cultures?",keywords:["ambivalence","creative","resistance","border","site"],explanation:"'This hybrid space...is a site of both ambivalence and creative resistance.'"}]},
  {id:"c1_10",level:"C1",title:"The Microbiome",topic:"Biology",passage:"The human microbiome — the trillions of microorganisms inhabiting the body, particularly the gut — is increasingly recognised as a critical component of health. Far from being passive residents, gut bacteria actively participate in digestion, synthesise vitamins, regulate the immune system, and even influence mood via the gut-brain axis. Disruptions to the microbiome, known as dysbiosis, have been associated with conditions ranging from inflammatory bowel disease to obesity and depression. Modern lifestyles — including antibiotic overuse, highly processed diets, and reduced exposure to natural environments — are thought to impoverish microbial diversity. Researchers are investigating probiotics, prebiotics, and faecal transplants as therapeutic interventions.",questions:[{type:"mcq",q:"What is the gut-brain axis?",options:["A surgical procedure","The pathway through which gut bacteria influence mood","A type of probiotic treatment","The connection between diet and intelligence"],answer:1,explanation:"'gut bacteria...influence mood via the gut-brain axis.'"},{type:"mcq",q:"What is dysbiosis?",options:["A vitamin deficiency","Over-production of gut bacteria","Disruption to the microbiome","A form of probiotic"],answer:2,explanation:"'Disruptions to the microbiome, known as dysbiosis, have been associated with conditions...'"},{type:"qa",q:"What aspects of modern lifestyles are thought to harm the microbiome?",keywords:["antibiotic","processed","diversity","natural","impoverish"],explanation:"'antibiotic overuse, highly processed diets, and reduced exposure to natural environments are thought to impoverish microbial diversity.'"}]},

  // ── C2 extra ──
  {id:"c2_5",level:"C2",title:"The Anthropocene",topic:"Science",passage:"Geologists have proposed designating the current epoch the Anthropocene — a term acknowledging that human activity has become the dominant force shaping Earth's geology and ecosystems. Stratigraphic evidence includes novel radioisotopes from nuclear testing, a ubiquitous layer of microplastics, altered nitrogen and phosphorus cycles, and accelerating species extinction. The designation, while not yet formally ratified, carries profound philosophical weight: it compels humanity to confront its status as a geological actor responsible for consequences extending across millennia. Critics of the term argue that it risks naturalising environmental destruction by framing it as an epoch rather than a crisis demanding urgent political response.",questions:[{type:"mcq",q:"What stratigraphic evidence supports the Anthropocene designation?",options:["Volcanic activity increases","Radioisotopes, microplastics, and altered biogeochemical cycles","Shifts in tectonic plates","Variations in solar output"],answer:1,explanation:"'Stratigraphic evidence includes novel radioisotopes...microplastics, altered nitrogen and phosphorus cycles, and accelerating species extinction.'"},{type:"mcq",q:"What risk do critics identify in using the term Anthropocene?",options:["It exaggerates human power","It naturalises environmental destruction by framing it as an epoch","It ignores geological evidence","It places blame on individual humans"],answer:1,explanation:"'it risks naturalising environmental destruction by framing it as an epoch rather than a crisis.'"},{type:"qa",q:"What philosophical implication does the Anthropocene designation carry?",keywords:["geological actor","responsibility","millennia","confront","consequences"],explanation:"'It compels humanity to confront its status as a geological actor responsible for consequences extending across millennia.'"}]},
  {id:"c2_6",level:"C2",title:"Moral Relativism",topic:"Philosophy",passage:"Moral relativism is the metaethical position that moral judgements are true or false only relative to a particular cultural or individual framework, with no universal standards to adjudicate between them. Descriptive relativism merely observes that moral beliefs vary across cultures; normative relativism goes further, claiming that this diversity is itself morally significant and that external moral critique is unwarranted. Philosophers such as James Rachels have challenged relativism by noting that it entails paralysing consequences: if morality is purely relative, we cannot condemn historical atrocities or argue for human rights. Proponents counter that universalism masks culturally specific values as objective truths, serving ideological ends.",questions:[{type:"mcq",q:"What distinguishes normative from descriptive relativism?",options:["Descriptive relativism denies moral variation","Normative relativism merely observes moral diversity","Normative relativism claims external moral critique is unwarranted","They are identical positions"],answer:2,explanation:"'Descriptive relativism merely observes that moral beliefs vary...normative relativism goes further, claiming...external moral critique is unwarranted.'"},{type:"mcq",q:"What paralysing consequence of relativism does Rachels identify?",options:["It makes ethical debate impossible","We cannot condemn historical atrocities or argue for human rights","It leads to moral nihilism only","It collapses all moral distinctions"],answer:1,explanation:"'if morality is purely relative, we cannot condemn historical atrocities or argue for human rights.'"},{type:"qa",q:"How do proponents of relativism respond to universalist arguments?",keywords:["universalism","masks","culturally specific","ideological","objective"],explanation:"'universalism masks culturally specific values as objective truths, serving ideological ends.'"}]},
  {id:"c2_7",level:"C2",title:"Dark Matter and Cosmology",topic:"Science",passage:"Approximately 27 percent of the universe is believed to consist of dark matter — a substance that interacts gravitationally but emits, absorbs, or reflects no electromagnetic radiation, rendering it invisible to current instruments. Its existence is inferred from the anomalous rotation curves of galaxies, gravitational lensing observations, and the large-scale structure of the cosmos. Despite decades of research, dark matter has not been directly detected; its constituent particle — whether an axion, a weakly interacting massive particle (WIMP), or something entirely novel — remains unknown. The failure to detect WIMPs at particle accelerators has prompted cosmologists to broaden theoretical frameworks substantially.",questions:[{type:"mcq",q:"How do scientists infer the existence of dark matter?",options:["By observing its light emissions","Through direct laboratory experiments","From gravitational effects, galaxy rotation curves, and lensing","By measuring its radioactive decay"],answer:2,explanation:"'Its existence is inferred from the anomalous rotation curves of galaxies, gravitational lensing observations, and the large-scale structure of the cosmos.'"},{type:"mcq",q:"What has prompted cosmologists to broaden their theoretical frameworks?",options:["Discovery of a new particle","Dark matter emitting unexpected radiation","Failure to detect WIMPs at accelerators","Confirmation of the axion model"],answer:2,explanation:"'The failure to detect WIMPs at particle accelerators has prompted cosmologists to broaden theoretical frameworks substantially.'"},{type:"qa",q:"What is the fundamental challenge that dark matter presents to physics?",keywords:["invisible","detect","particle","unknown","electromagnetic"],explanation:"Dark matter 'emits, absorbs, or reflects no electromagnetic radiation,' making it undetectable with current instruments, and its constituent particle 'remains unknown.'"}]},
  {id:"c2_8",level:"C2",title:"The Limits of Language",topic:"Linguistics",passage:"Wittgenstein's later philosophy introduced the concept of language games — the idea that words acquire meaning not from picturing facts but from their use within specific forms of life. This fundamentally challenged the representationalist view that language is a mirror of reality. The Sapir-Whorf hypothesis, in its strong form, proposes that the language one speaks shapes — or even determines — the categories in which one thinks. Empirical evidence supports a weaker version: speakers of languages with richer spatial or temporal vocabulary do show measurable differences in cognitive tasks. Yet critics contend that the universality of certain logical concepts across languages suggests cognitive architecture independent of linguistic structures.",questions:[{type:"mcq",q:"What does Wittgenstein's concept of 'language games' argue?",options:["Language mirrors reality precisely","Words gain meaning from their use within specific forms of life","All languages are logically equivalent","Meaning is determined by grammar alone"],answer:1,explanation:"'words acquire meaning not from picturing facts but from their use within specific forms of life.'"},{type:"mcq",q:"What does evidence support regarding the Sapir-Whorf hypothesis?",options:["The strong form — language determines thought","The hypothesis is entirely false","A weaker version — richer vocabulary correlates with cognitive differences","No relation between language and cognition"],answer:2,explanation:"'Empirical evidence supports a weaker version: speakers of languages with richer...vocabulary do show measurable differences in cognitive tasks.'"},{type:"qa",q:"What evidence do critics use to challenge the strong Sapir-Whorf hypothesis?",keywords:["universality","logical","cognitive architecture","independent","languages"],explanation:"'the universality of certain logical concepts across languages suggests cognitive architecture independent of linguistic structures.'"}]},
  {id:"c2_9",level:"C2",title:"Free Will and Determinism",topic:"Philosophy",passage:"The problem of free will asks whether human choices are genuinely self-originated or merely the inevitable product of prior causes — neural states, genetics, upbringing, and physical laws. Hard determinists argue that every event, including mental states, is causally necessitated; free will is thus an illusion. Libertarians (in the metaphysical sense) maintain that at least some actions escape causal determination, perhaps via quantum indeterminacy or irreducible agency. Compatibilists offer a middle path: free will and determinism are not mutually exclusive; genuine freedom consists in acting according to one's own desires and reasons unimpeded by external coercion, regardless of whether those desires are causally determined.",questions:[{type:"mcq",q:"What is the compatibilist position on free will?",options:["Free will is a complete illusion","Quantum mechanics makes all actions free","Free will and determinism can coexist — freedom means acting on one's own desires uncoerced","Only libertarianism preserves genuine freedom"],answer:2,explanation:"'Compatibilists offer a middle path: free will and determinism are not mutually exclusive; genuine freedom consists in acting according to one's own desires...unimpeded by external coercion.'"},{type:"mcq",q:"How do libertarians (metaphysical) argue against hard determinism?",options:["By denying causality altogether","By claiming quantum indeterminacy or irreducible agency allows some actions to escape causal determination","By accepting determinism but denying its moral implications","By arguing consciousness is non-physical"],answer:1,explanation:"'Libertarians...maintain that at least some actions escape causal determination, perhaps via quantum indeterminacy or irreducible agency.'"},{type:"qa",q:"What does hard determinism conclude about the nature of free will?",keywords:["illusion","causally necessitated","prior causes","mental states"],explanation:"'Hard determinists argue that every event, including mental states, is causally necessitated; free will is thus an illusion.'"}]},
  {id:"c2_10",level:"C2",title:"Tragedy and Catharsis",topic:"Literature",passage:"Aristotle defined tragedy as an imitation of a serious, complete action of sufficient magnitude, effecting through pity and fear the catharsis of such emotions. The notion of catharsis — typically translated as purging or purification — has generated centuries of scholarly debate. Some interpret it medically: tragedy evacuates pent-up emotions, restoring psychological equilibrium. Others read it cognitively: through engaging with fictional suffering, audiences refine their emotional intelligence and moral understanding. Nietzsche challenged the Aristotelian account entirely, arguing that tragedy's power lies not in purging suffering but in affirming it — confronting the Dionysian chaos of existence without retreating into comforting illusions. Contemporary theorists draw on both traditions to analyse how narrative art mediates human responses to mortality and injustice.",questions:[{type:"mcq",q:"What is the medical interpretation of catharsis?",options:["Tragedy teaches moral lessons","Tragedy evacuates pent-up emotions, restoring psychological equilibrium","Tragedy reinforces social norms","Tragedy provides intellectual pleasure only"],answer:1,explanation:"'Some interpret it medically: tragedy evacuates pent-up emotions, restoring psychological equilibrium.'"},{type:"mcq",q:"How does Nietzsche's view of tragedy differ from Aristotle's?",options:["He agreed catharsis purges suffering","He argued tragedy's power lies in affirming rather than purging suffering","He claimed tragedy was morally harmful","He rejected all emotional responses to art"],answer:1,explanation:"'Nietzsche...arguing that tragedy's power lies not in purging suffering but in affirming it.'"},{type:"qa",q:"What do contemporary theorists examine, drawing on both Aristotelian and Nietzschean traditions?",keywords:["narrative","mediates","mortality","injustice","responses"],explanation:"'Contemporary theorists...analyse how narrative art mediates human responses to mortality and injustice.'"}]},
];
